# permissions for end users to edit badgerequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: my-kubebuilder-project
    app.kubernetes.io/managed-by: kustomize
  name: badgerequest-editor-role
rules:
- apiGroups:
  - badges.example.com
  resources:
  - badgerequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - badges.example.com
  resources:
  - badgerequests/status
  verbs:
  - get
